### ISSUE TITLE
desk page: NullPointerException when not logged in

### ISSUE THREAD

**Issue by cliffdurden** [khasang-incubator/stock_manager#4]
при попытке открыть страничку desk вылетает ошибка NPE если мы не залогинились перед этим

**Comment by Buranzo** [comment]
Строка 35: Long userId = userDAO.getUserIdByLogin(SecurityContextHolder.getContext().getAuthentication().getName());
вызывает ошибку NPE при не авторизованном пользователе.
Эта строка была введена другой группой, которая занимается "Продуктами". Т.к. у них завязка идет на выборку из БД, думаю будет разумно не самим править их код, а подключить автора изменений к данной ошибке.
Т.к. не знаю его никнэйм в проекте–сбросил ему сообщение через скайп.
P.S. В принципе, можно вообще подумать о целесообразности показа страницы DESK не авторизованному пользователю.

**Comment by yuoknow** [comment]
Исправил.

**Comment by cliffdurden** [comment]
да, ошибка перестала вылетать
